# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gvr_marker_call_rate <- function(geno) {
    .Call(`_easybreedeR_gvr_marker_call_rate`, geno)
}

gvr_individual_call_rate <- function(geno) {
    .Call(`_easybreedeR_gvr_individual_call_rate`, geno)
}

gvr_maf <- function(geno) {
    .Call(`_easybreedeR_gvr_maf`, geno)
}

gvr_individual_het <- function(geno) {
    .Call(`_easybreedeR_gvr_individual_het`, geno)
}

gvr_marker_het <- function(geno) {
    .Call(`_easybreedeR_gvr_marker_het`, geno)
}

gvr_hwe_exact <- function(geno) {
    .Call(`_easybreedeR_gvr_hwe_exact`, geno)
}

gvr_relatedness_pairs <- function(geno, sample_ids, max_pairs = 2147483647L, max_markers = 2147483647L, min_valid = 20L) {
    .Call(`_easybreedeR_gvr_relatedness_pairs`, geno, sample_ids, max_pairs, max_markers, min_valid)
}

fast_pedigree_qc <- function(ids, sires, dams) {
    .Call(`_easybreedeR_fast_pedigree_qc`, ids, sires, dams)
}

fast_pedigree_qc_sex <- function(ids, sires, dams, sex) {
    .Call(`_easybreedeR_fast_pedigree_qc_sex`, ids, sires, dams, sex)
}

fast_detect_loops <- function(ids, sires, dams) {
    .Call(`_easybreedeR_fast_detect_loops`, ids, sires, dams)
}

fast_find_deepest_ancestor <- function(ids, sires, dams, sample_size = 200L) {
    .Call(`_easybreedeR_fast_find_deepest_ancestor`, ids, sires, dams, sample_size)
}

check_birth_date_order <- function(ids, sires, dams, birth_dates) {
    .Call(`_easybreedeR_check_birth_date_order`, ids, sires, dams, birth_dates)
}

fast_lap_distribution <- function(ids, sires, dams, sample_size = 10000L, max_depth = 20L) {
    .Call(`_easybreedeR_fast_lap_distribution`, ids, sires, dams, sample_size, max_depth)
}

fast_lap_depths <- function(ids, sires, dams) {
    .Call(`_easybreedeR_fast_lap_depths`, ids, sires, dams)
}

fast_descendant_summary <- function(ids, parent_vals, max_depth = 50L) {
    .Call(`_easybreedeR_fast_descendant_summary`, ids, parent_vals, max_depth)
}

fast_inbreeding_cpp <- function(ids, sires, dams) {
    .Call(`_easybreedeR_fast_inbreeding_cpp`, ids, sires, dams)
}

fast_top_contrib_cpp <- function(ids, sires, dams, F, target_id, max_depth = 6L, top_k = 5L) {
    .Call(`_easybreedeR_fast_top_contrib_cpp`, ids, sires, dams, F, target_id, max_depth, top_k)
}

eb_ped_to_blup_codes_cpp <- function(allele1, allele2) {
    .Call(`_easybreedeR_eb_ped_to_blup_codes_cpp`, allele1, allele2)
}

