name: Build JOSS paper

on:
  push:
    paths:
      - paper/**
  pull_request:
    paths:
      - paper/**

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build paper
        uses: openjournals/openjournals@v1.4
        with:
          journal: joss
          paper-path: paper/paper.md
